### ISSUE TITLE
ImportError: No module named hapitime

### ISSUE THREAD

**Issue by angelgutarra** [hapi-server/client-python#36]
I downloaded the package into a fresh Conda environment running python 2.7.18 
```bash
pip install 'git+https://github.com/hapi-server/client-python' --upgrade
```
which successfully built hapiclient. 

then opened python and ran the following code which prompted the error. 
```python
>>> from hapiclient import hapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Angel/opt/anaconda3/envs/hapitest/lib/python2.7/site-packages/hapiclient/__init__.py", line 2, in <module>
    from hapiclient.hapi import hapi
  File "/Users/Angel/opt/anaconda3/envs/hapitest/lib/python2.7/site-packages/hapiclient/hapi.py", line 15, in <module>
    from hapiclient.hapitime import hapitime2datetime, hapitime_reformat
ImportError: No module named hapitime
```

**Comment by rweigel** [comment]
I am not able to reproduce using

```
conda create --name python2.7-test python=2.7
conda activate python2.7-test
pip install 'git+https://github.com/hapi-server/client-python' --upgrade
python -c 'import sys;print(sys.version);from hapiclient import hapi;help(hapi)'
```

**Comment by GaryQ-physics** [comment]
I got the same thing as angelgutarra. 

```
(base) $ conda create --name hapitest python=2.7
(base) $ conda activate hapitest
(hapitest) $ pip install 'git+https://github.com/hapi-server/client-python' --upgrade
(hapitest) $ python -c 'import sys;print(sys.version);from hapiclient import hapi;help(hapi)'

2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:42:48) 
[GCC 7.3.0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gary/miniconda3/envs/hapitest/lib/python2.7/site-packages/hapiclient/__init__.py", line 2, in <module>
    from hapiclient.hapi import hapi
  File "/home/gary/miniconda3/envs/hapitest/lib/python2.7/site-packages/hapiclient/hapi.py", line 15, in <module>
    from hapiclient.hapitime import hapitime2datetime, hapitime_reformat
ImportError: No module named hapitime
```

note I am using miniconda with version conda 4.9.2

**Comment by angelgutarra** [comment]
I reran the same commands but still came to the same error. 

```
(base) Angels-2015-MBP:~ Angel$ conda activate python2.7-test
(python2.7-test) Angels-2015-MBP:~ Angel$ pip install 'git+https://github.com/hapi-server/client-python' --upgrade
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/hapi-server/client-python
  Cloning https://github.com/hapi-server/client-python to /private/var/folders/9n/rywnl1qs74sgq37861ydlf8c0000gn/T/pip-req-build-pDvTiN
  Running command git clone -q https://github.com/hapi-server/client-python /private/var/folders/9n/rywnl1qs74sgq37861ydlf8c0000gn/T/pip-req-build-pDvTiN
Collecting isodate>=0.6.0
  Using cached https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl
Collecting urllib3
  Using cached https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl
Collecting joblib
  Using cached https://files.pythonhosted.org/packages/28/5c/cf6a2b65a321c4a209efcdf64c2689efae2cb62661f8f6f4bb28547cf1bf/joblib-0.14.1-py2.py3-none-any.whl
Collecting pandas<0.25,>=0.23
  Using cached https://files.pythonhosted.org/packages/52/ff/912fe03a623a70bcf297d466013a0b4f4c68c3b60f86bf226682d061fc09/pandas-0.24.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy<1.17
  Using cached https://files.pythonhosted.org/packages/09/96/84cf406fe7d589f3dba9fc0f737e65985a3526c6d8c783f02d4b5a10825d/numpy-1.16.6-cp27-cp27m-macosx_10_9_x86_64.whl
Collecting pyparsing<3
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting zipp<3
  Using cached https://files.pythonhosted.org/packages/96/0a/67556e9b7782df7118c1f49bdc494da5e5e429c93aa77965f33e81287c8c/zipp-1.2.0-py2.py3-none-any.whl
Collecting kiwisolver<=1.1
  Using cached https://files.pythonhosted.org/packages/0d/15/ec5f70ac79f378ed0ef5ed8b71e8a04e382115426b2cda9a3ab5ffcf467f/kiwisolver-1.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting six
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.5.0
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting pytz>=2011k
  Using cached https://files.pythonhosted.org/packages/89/06/2c2d3034b4d6bf22f2a4ae546d16925898658a33b4400cfb7e2c1e2871a3/pytz-2020.5-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3.4"
  Using cached https://files.pythonhosted.org/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: setuptools in ./opt/anaconda3/envs/python2.7-test/lib/python2.7/site-packages (from kiwisolver<=1.1->hapiclient==0.1.9b0) (44.0.0.post20200106)
Building wheels for collected packages: hapiclient
  Building wheel for hapiclient (setup.py) ... done
  Created wheel for hapiclient: filename=hapiclient-0.1.9b0-cp27-none-any.whl size=25416 sha256=2862e178c03a9d3000a42b41196530d4de8e6b9d8b9f7f521a51472c88c55c1e
  Stored in directory: /private/var/folders/9n/rywnl1qs74sgq37861ydlf8c0000gn/T/pip-ephem-wheel-cache-V2aqMX/wheels/ac/ff/b7/78a52b1533cbdd4a6b05c50c9d05f421d757e1473869c2d00a
Successfully built hapiclient
Installing collected packages: six, isodate, urllib3, joblib, python-dateutil, pytz, numpy, pandas, pyparsing, contextlib2, zipp, kiwisolver, hapiclient
Successfully installed contextlib2-0.6.0.post1 hapiclient-0.1.9b0 isodate-0.6.0 joblib-0.14.1 kiwisolver-1.1.0 numpy-1.16.6 pandas-0.24.2 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.5 six-1.15.0 urllib3-1.26.2 zipp-1.2.0
(python2.7-test) Angels-2015-MBP:~ Angel$ 
(python2.7-test) Angels-2015-MBP:~ Angel$ 
(python2.7-test) Angels-2015-MBP:~ Angel$ python -c 'import sys;print(sys.version);from hapiclient import hapi;help(hapi)'
2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 17:44:47) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Angel/opt/anaconda3/envs/python2.7-test/lib/python2.7/site-packages/hapiclient/__init__.py", line 2, in <module>
    from hapiclient.hapi import hapi
  File "/Users/Angel/opt/anaconda3/envs/python2.7-test/lib/python2.7/site-packages/hapiclient/hapi.py", line 15, in <module>
    from hapiclient.hapitime import hapitime2datetime, hapitime_reformat
ImportError: No module named hapitime
```


I looked for differences between the old hapi.py that I had in my old anaconda env and compared it to the new hapi.py in the new anaconda env and found the following. The old hapi.py defines hapitime2datetime function inside of the hapi.py file whereas the new hapi.py tries to import it on line 15. The two files can be found in the attachments. 


[old_hapi.py.txt](https://github.com/hapi-server/client-python/files/5837601/old_hapi.py.txt)
[new_hapi.py.txt](https://github.com/hapi-server/client-python/files/5837602/new_hapi.py.txt)

**Comment by GaryQ-physics** [comment]
It's now working for me

**Comment by angelgutarra** [comment]
works for me too. thanks.
